- id: sbt-scalafmt
  name: Sbt scalafmt formatter
  stages: [commit]
  language: python
  entry: sbt-scalafmt
  always_run: true
  require_serial: true
  pass_filenames: false
  minimum_pre_commit_version: '1.13.0'
